from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata

block_cipher = None

a = Analysis(['main.py'],
             pathex=['C:\\Users\\nicol\\OneDrive\\Canal Youtube\\PyTax\\Interface - Pyside2\\Project_01_system'],
             binaries=[],
             datas=collect_data_files('PySide2'),
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='icone.ico')

# Força a copia das bibliotecas DLL necessárias
import os
import PyInstaller.__main__

PyInstaller.__main__.run([
    '--name=%s' % 'main',
    '--add-data=%s' % ';'.join(collect_data_files('PySide2')),
    '--hidden-import', 'PySide2.QtXml',
    '--hidden-import', 'PySide2.QtSql',
    '--hidden-import', 'PySide2.QtSvg',
    '--hidden-import', 'PySide2.QtPrintSupport',
    '--hidden-import', 'PySide2.QtNetwork',
    '--hidden-import', 'PySide2.QtMultimediaWidgets',
    '--hidden-import', 'PySide2.QtMultimedia',
    '--hidden-import', 'PySide2.QtLocation',
    '--hidden-import', 'PySide2.QtHelp',
    '--hidden-import', 'PySide2.QtDesigner',
    '--hidden-import', 'PySide2.QtBluetooth',
    '--hidden-import', 'PySide2.QtWebKit',
    '--hidden-import', 'PySide2.QtWebKitWidgets',
    '--hidden-import', 'PySide2.QtWebSockets',
    '--hidden-import', 'PySide2.QtWebEngineWidgets',
    '--hidden-import', 'PySide2.QtWebEngineCore',
    '--hidden-import', 'PySide2.QtWebEngine',
    '--hidden-import', 'PySide2.QtTest',
    '--hidden-import', 'PySide2.QtSvg',
    '--hidden-import', 'PySide2.QtQuickWidgets',
    '--hidden-import', 'PySide2.QtQuickTest',
    '--hidden-import', 'PySide2.QtQuick',
    '--hidden-import', 'PySide2.QtQml',
    '--hidden-import', 'PySide2.QtPositioning',
    '--hidden-import', 'PySide2.QtOpenGL',
    '--hidden-import', 'PySide2.QtNetworkAuth',
    '--hidden-import', 'PySide2.QtMultimediaQuick',
    '--hidden-import', 'PySide2.QtMultimediaWidgets',
    '--hidden-import', 'PySide2.QtMultimedia',
    '--hidden-import', 'PySide2.QtLocation',
    '--hidden-import', 'PySide2.QtHelp',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtCore',
    '--hidden-import', 'PySide2.QtWidgets',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtBluetooth',
    '--hidden-import', 'PySide2.QtWebEngineWidgets',
    '--hidden-import', 'PySide2.QtWebEngineCore',
    '--hidden-import', 'PySide2.QtWebEngine',
    '--hidden-import', 'PySide2.QtTest',
    '--hidden-import', 'PySide2.QtSvg',
    '--hidden-import', 'PySide2.QtQml',
    '--hidden-import', 'PySide2.QtQuickWidgets',
    '--hidden-import', 'PySide2.QtQuickTest',
    '--hidden-import', 'PySide2.QtQuick',
    '--hidden-import', 'PySide2.QtPositioning',
    '--hidden-import', 'PySide2.QtOpenGL',
    '--hidden-import', 'PySide2.QtNetworkAuth',
    '--hidden-import', 'PySide2.QtMultimediaQuick',
    '--hidden-import', 'PySide2.QtMultimediaWidgets',
    '--hidden-import', 'PySide2.QtMultimedia',
    '--hidden-import', 'PySide2.QtLocation',
    '--hidden-import', 'PySide2.QtHelp',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtCore',
    '--hidden-import', 'PySide2.QtWidgets',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtBluetooth',
    '--hidden-import', 'PySide2.QtWebEngineWidgets',
    '--hidden-import', 'PySide2.QtWebEngineCore',
    '--hidden-import', 'PySide2.QtWebEngine',
    '--hidden-import', 'PySide2.QtTest',
    '--hidden-import', 'PySide2.QtSvg',
    '--hidden-import', 'PySide2.QtQml',
    '--hidden-import', 'PySide2.QtQuickWidgets',
    '--hidden-import', 'PySide2.QtQuickTest',
    '--hidden-import', 'PySide2.QtQuick',
    '--hidden-import', 'PySide2.QtPositioning',
    '--hidden-import', 'PySide2.QtOpenGL',
    '--hidden-import', 'PySide2.QtNetworkAuth',
    '--hidden-import', 'PySide2.QtMultimediaQuick',
    '--hidden-import', 'PySide2.QtMultimediaWidgets',
    '--hidden-import', 'PySide2.QtMultimedia',
    '--hidden-import', 'PySide2.QtLocation',
    '--hidden-import', 'PySide2.QtHelp',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtCore',
    '--hidden-import', 'PySide2.QtWidgets',
    '--hidden-import', 'PySide2.QtGui',
    '--hidden-import', 'PySide2.QtBluetooth',
    '--hidden-import', 'PySide2.QtWebEngineWidgets',
    '--hidden-import', 'PySide2.QtWebEngineCore',
    '--hidden-import', 'PySide2.QtWebEngine',
    '--hidden-import', 'PySide2.QtTest',
    '--hidden-import', 'PySide2.QtSvg',
    '--hidden-import', 'PySide2.QtQml',
    '--hidden-import', 'PySide2.QtQuickWidgets',
    '--hidden-import', 'PySide2.QtQuickTest',
    '--hidden-import', 'PySide2.QtQuick',
    '--hidden-import', 'PySide2.QtPositioning',
    '--hidden-import', 'PySide2.QtOpenGL',
    '--hidden-import', 'PySide2.QtNetworkAuth',
    '--hidden-import', 'PySide2.QtMultimediaQuick',
